//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PioneerTestConsultancySystem.PioneerServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PioneerServiceReference.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/insertemployee", ReplyAction="http://tempuri.org/IService1/insertemployeeResponse")]
        int insertemployee(PioneerTest.Models.EmployeeDetailsModel employee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/insertemployee", ReplyAction="http://tempuri.org/IService1/insertemployeeResponse")]
        System.Threading.Tasks.Task<int> insertemployeeAsync(PioneerTest.Models.EmployeeDetailsModel employee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/inserteducation", ReplyAction="http://tempuri.org/IService1/inserteducationResponse")]
        int inserteducation(PioneerTest.Models.EducationDetailsModel education);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/inserteducation", ReplyAction="http://tempuri.org/IService1/inserteducationResponse")]
        System.Threading.Tasks.Task<int> inserteducationAsync(PioneerTest.Models.EducationDetailsModel education);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : PioneerTestConsultancySystem.PioneerServiceReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<PioneerTestConsultancySystem.PioneerServiceReference.IService1>, PioneerTestConsultancySystem.PioneerServiceReference.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int insertemployee(PioneerTest.Models.EmployeeDetailsModel employee) {
            return base.Channel.insertemployee(employee);
        }
        
        public System.Threading.Tasks.Task<int> insertemployeeAsync(PioneerTest.Models.EmployeeDetailsModel employee) {
            return base.Channel.insertemployeeAsync(employee);
        }
        
        public int inserteducation(PioneerTest.Models.EducationDetailsModel education) {
            return base.Channel.inserteducation(education);
        }
        
        public System.Threading.Tasks.Task<int> inserteducationAsync(PioneerTest.Models.EducationDetailsModel education) {
            return base.Channel.inserteducationAsync(education);
        }
    }
}
